=== DragonZ2013/MAP_Sem10/src/Main/restaurant.dtd
<?xml version="1.0" encoding="UTF-8" ?>
    <!ELEMENT restaurant (name) (location)+>
    <!ELEMENT location (name)? (address) (schedule)* (dailymenu)+>
    <!ATTLIST schedule day CDATA #REQUIRED>
    <!ELEMENT schedule (opentime) (closetime)>
    <!ELEMENT opentime (#PCDATA)>
    <!ELEMENT closetime (#PCDATA)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT address (city) (street) (number)>
    <!ELEMENT city (#PCDATA)>
    <!ELEMENT street (#PCDATA)>
    <!ELEMENT number (#PCDATA)>
    <!ELEMENT dailymenu (date) (food)+>
    <!ELEMENT date (#PCDATA)>
    <!ELEMENT food (review)?>
    <!ATTLIST food foodname CDATA #REQUIRED foodtype CDATA ("Primary"|"Starter") "Primary" #REQUIRED>
    <!ELEMENT review (comment)?>
    <!ATTLIST review points CDATA #REQUIRED>
    <!ELEMENT comment (#PCDATA)>

=== DragonZ2013/MAP_Sem10/src/Main/restaurant_example.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE restaurant SYSTEM "restaurant.dtd">
<restaurant>
    <name>Restaurant Name</name>
    <location>
        <name>Location Name</name>
        <address>
            <city>Brasov</city>
            <street>Calea Bucuresti</street>
            <number>40</number>
        </address>
        <schedule day="Monday">
            <opentime>08:00</opentime>
            <closetime>18:00</closetime>
        </schedule>
        <schedule day="Tuesday">
            <opentime>09:00</opentime>
            <closetime>20:00</closetime>
        </schedule>
        <dailymenu>
            <date>12/7/2021</date>
            <food foodname="Potatoes" foodtype="Starter">
                <review points="5">
                    <comment>Generic but quality</comment>
                </review>
            </food>
        </dailymenu>
        <dailymenu>
            <date>12/8/2021</date>
            <food foodname="Steak">
                <review points="4.5"></review>
            </food>
            <food foodname="Ribs">
            </food>
            <food foodname="Soup" foodtype="Starter">
            </food>
        </dailymenu>
    </location>

</restaurant>
